### ISSUE TITLE
[Feature] Ballot Voting Box by Role

### ISSUE THREAD

**Issue by okiave** [Crypto-Link-Payments/crypto-link#95]
As a Discord DAO member, I want specific Community role holders to initiate and propose a ballot box to vote for/against something using their non-custodial  supported wallet holding specific Stellar Assets supported by CrptoLink.

**Comment by AnimusXCASH** [comment]
@okiave I have just finished with coding the whole system, and will be deployed today to testnet. Testing will happen on Crypto Link server so give me a ping if you would like to participate and comment. 

brg

**Comment by AnimusXCASH** [comment]
It seems that voting system works ✔️
